name: Candy Countdown

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,10,11 * * 1-5"

jobs:
  build:
    environment: fyo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a PS script
        shell: pwsh
        run: ./PSScripts/Start-CandyCountdown.ps1 -Webhook "${{ secrets.webhook }}"
