name: Lint Code Base

on:
  pull_request:
    branches:
      - main

jobs:
  super-linter:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Super-linter
      uses: super-linter/super-linter/slim@v7.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
