name: Lint Code Base

on:
  pull_request:
    branches:
      - main

jobs:
  super-linter:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Full Git history is needed to get a proper list of changed files


    - name: Super-linter
      uses: super-linter/super-linter/slim@v7.3.0
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # VALIDATE_ALL_CODEBASE: false
        # VALIDATE_JSCPD: false
        # VALIDATE_KUBERNETES_KUBEVAL: false
        VALIDATE_CHECKOV: true
        VALIDATE_JSON_PRETTIER: true
        VALIDATE_YAML_PRETTIER: true
        VALIDATE_POWERSHELL: true
